[project]
name = "teaws"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "paddleocr>=3.3.2",
    "paddlepaddle",
    "paddlex[ocr]>=3.3.9",
    "safetensors>=0.6.2",
    "openai>=1.3.0",
]
